### PR TITLE
Update namaskar.sh

### PR DESCRIPTION
**Pull request by stuffbymax**
added ram and swap

### CODE REVIEW

**Comment by Piyush-linux** [comment]
Looks Little Issue !
 
Screenshot_2024-06-30-23-09-34_1920x1080

**Comment by stuffbymax** [comment]
I am lazy to do more colours sorry

If you give me some time it will be fix

**Comment by stuffbymax** [comment]
The line 39 or the colours sorry i am stupid

**Comment by Piyush-linux** [comment]
@stuffbymax 
Plz try some other colours and align the text in pretty format :)

**Comment by stuffbymax** [comment]
OK

**Comment by stuffbymax** [comment]
done i think

**Comment by Piyush-linux** [comment]
You Have Created Other PR , 
So I'm Closing This One

**Pull request closed without merging**
